### ISSUE TITLE
Accessible font

### ISSUE THREAD

**Issue by oscar230** [oscar230/hathor#13]
Use accessible font, make it togglable, off by default.
https://www.dyslexiefont.com/

**Comment by manoj1749** [comment]
could you elobarate what we are needed to be done here

**Comment by oscar230** [comment]
Hi @manoj1749 , I was thinking about implementing a switch or a user setting for switching fonts in the web interface.
Since creating this issue I found out that maybe https://opendyslexic.org/ will work better. Although I'm not so sure if the fonts actually work after contacting some friends with knowledge regarding this. Therefore I will close this issue. Thank you for your interest.
